version: '3'

services:

  #=====================#
  # PHP7
  #=====================#
  php:
    container_name: php72
    build:
      context: .docker/php
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - 9000:9000
    user: ${LOCAL_USER}
    volumes:
      - .:/var/www/app
      - .docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/volumes/app/logs:/var/www/app/var/log

  #=====================#
  # nginx
  #=====================#
  engine:
    container_name: nginx
    build:
      context: .docker/nginx
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - .:/var/www/app #:cached
      - .docker/nginx/portfolio.conf:/etc/nginx/conf.d/site.conf:ro
      - .docker/volumes/nginx/logs:/var/log/nginx/
      - /var/www/app/vendor/ #:delegated
    depends_on:
      - php

  #=====================#
  # MySQL 5.7
  #=====================#
  database:
    container_name: mysql57
    build:
      context: .docker/mysql
    restart: on-failure
    env_file:
      - .env.local
    ports:
      - 3306:3306
    volumes:
      - .docker/volumes/portfoliodb:/var/lib/mysql
    depends_on:
      - php

  #=====================#
  # Adminer
  #=====================#
  adminer:
    container_name: adminer
    image: adminer
    restart: on-failure
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - database
